[bindings.kotlin]
package_name = "org.opentimestamps"
cdylib_name = "otsffi"

[bindings.kotlin-native]
package_name = "org.opentimestamps"
cdylib_name = "otsffi"

[bindings.swift]
cdylib_name = "otsffi"