on:
  push:
    branches:
      - master
  pull_request: {}
  
name: Build Bindings iOS
    
jobs:
  build-bindings:
    runs-on: macOS-latest
    name: build

    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v4
        
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
      - run: cargo install cargo-lipo just
      - run: source env.sh
      
      - name: Build sdk bindings
        working-directory: ots_bindings/
        run: just swift-ios

      - name: Archive release
        uses: actions/upload-artifact@v3
        with:
          name: otsffi-ios
          path: |
             ots_bindings/ffi/swift-ios
